config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :categories, only: [:only]
  resources :classifieds, only: [:new, :create, :index, :show]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :classifieds
end

app/models/classified.rb
class Classified < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  def index
    @classifieds = Classified.all
    @categories = Category.all
  end

  def new
    @classified = Classified.new
    @classified.build_category
  end

  def create
    @classified = Classified.new(safe_classified_params)
    @classified.build_category(safe_category_params)

    if @classified.save
      redirect_to classifieds_path
    else
      render 'new'
    end
  end

  def show
    @classified = Classified.find(params[:id])
  end

  private

  def safe_classified_params
    params.required(:classified).permit(:title, :price, :description)
  end

  def safe_category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/classified_helper.rb
module ClassifiedHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/classified/index.html.erb
<h1>Classifieds</h1>

<section>
  <% @classifieds.each do |classified| %>
  <article>
    <h2><<%= classified.title %></h2>
    <p><%= classified.description %>

    <div><<%= "$#{classified.price}" %></div>
    <div><%= classified.category %></div>
  <%end%>

</ul>

app/views/classified/new.html.erb
<h1>Create A Classified</h1>

<%= form_for @classified do |form| %>
<div>
    <%= form.label :title %>
    <%= form.text_field :title %>
</div>
<div>
  <%= form.label :description %>
  <%= form.textarea :description %>
</div>
<div>
  <%= field_for @classified.category do |category_form| %>
    <%= category_form.label :name %>
    <%= category_form.text_field :name %>
    <%=end%>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  

app/views/classifieds/index.html.erb
<h1>Classifieds</h1>

<section>
  <% @classifieds.each do |classified| %>
  <article class="well well-lg">
    <h2><<%= classified.title %></h2>
    <p><%= classified.description %>

    <div><<%= "$#{classified.price}" %></div>
    <div><%= classified.category.name %></div>
  </article>
  <%end%>
</section>

<section class="col-md-4">
  <article class="panel panel-primary">
    <div class="panel panel-heading">
      categories
    </div>
  <ul class="well well-lg">
  <% @categories.each do |category| %>
  <l1><h3><%= category.name %></h3></l1>
  <% end %>
</ul>
</article>
</section>

app/views/classifieds/new.html.erb
<h1>Create A Classified</h1>

<%= form_for @classified do |form| %>
<div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :description %>
  <%= form.text_area :description, class: "form-control" %>
</div>

<div class="form-group">
  <%= fields_for @classified.category do |category_form| %>
    <%= category_form.label :name %>
    <%= category_form.text_field :name, class: "form-control" %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>
  
  <%= form.submit "create Classified", class: "btn btn-primary btn-lg"%>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StuffFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
<div>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>


<%=link_to "Create New Classified", new_classified_path() %>
<%= link_to "View List of Classifieds", classifieds_path %>